import React from 'react';
import { RefreshCw, ShieldCheck, Award, AlertTriangle, CheckCircle, BookOpen } from 'lucide-react';
import PageHeader from '../../../components/ui/PageHeader';
import EmptyState from '../../../components/ui/EmptyState';
import Button from '../../../components/ui/Button';

export default function StudentSkillTests({
  techSkills,
  loadingTechSkills,
  activeTestSkill,
  generatingTest,
  testQuestions,
  testResult,
  currentQuestionIdx,
  selectedAnswers,
  submittingTest,
  handleStartSkillTest,
  handleSubmitSkillTest,
  setCurrentQuestionIdx,
  setSelectedAnswers,
  setActiveTestSkill,
  setTestResult
}) {
  const [filter, setFilter] = React.useState('all'); // 'all', 'verified', 'unverified'

  return (
    <div className="max-w-5xl mx-auto space-y-8 animate-fade-in">
      <PageHeader
        title="Your Skill Tests"
        subtitle="Verify your technical proficiency. Take a 10-question MCQ test generated by AI to earn a verified rating."
      />

      {/* 1. Loading MCQ Test generation */}
      {activeTestSkill && generatingTest && (
        <div className="p-8 bg-surface-container border border-outline-variant rounded-2xl flex flex-col items-center justify-center space-y-4 min-h-[400px]">
          <RefreshCw className="w-10 h-10 text-primary animate-spin" />
          <p className="text-sm font-bold text-on-surface">Generating 10 custom questions for {activeTestSkill}...</p>
          <p className="text-xs text-on-surface-variant max-w-sm text-center font-mono">
            Querying Claude API with Groq fallback. Crafting conceptual theory and code analysis questions...
          </p>
        </div>
      )}

      {/* 2. Active MCQ Test Mode */}
      {activeTestSkill && !generatingTest && testQuestions.length > 0 && !testResult && (
        <div className="bg-surface-container border border-outline-variant rounded-2xl p-8 space-y-6">
          <div className="flex justify-between items-center border-b border-outline-variant pb-4">
            <div>
              <span className="text-[10px] font-mono uppercase tracking-wider text-primary">Technical Verification Test</span>
              <h3 className="text-xl font-headline font-bold text-on-surface mt-1">{activeTestSkill} Assessment</h3>
            </div>
            <span className="px-3 py-1 bg-surface-container-high border border-outline-variant rounded-lg text-xs font-mono text-secondary">
              Question {currentQuestionIdx + 1} of 10
            </span>
          </div>

          {/* Progress Bar */}
          <div className="w-full bg-surface-container-low h-1.5 rounded-full overflow-hidden">
            <div 
              className="bg-primary h-full transition-all duration-300"
              style={{ width: `${((currentQuestionIdx + 1) / 10) * 100}%` }}
            ></div>
          </div>

          {/* Question Card */}
          <div className="p-6 bg-surface-container-low border border-outline-variant rounded-xl space-y-4">
            <p className="text-sm font-semibold text-on-surface leading-relaxed whitespace-pre-line">
              {testQuestions[currentQuestionIdx]?.question}
            </p>
          </div>

          {/* Options Grid */}
          <div className="grid grid-cols-1 gap-3">
            {testQuestions[currentQuestionIdx]?.options.map((opt, optIdx) => {
              const isSelected = selectedAnswers[currentQuestionIdx] === optIdx;
              return (
                <button
                  key={optIdx}
                  type="button"
                  onClick={() => {
                    setSelectedAnswers({
                      ...selectedAnswers,
                      [currentQuestionIdx]: optIdx
                    });
                  }}
                  className={`w-full text-left p-4 rounded-xl border text-xs transition-all flex items-center justify-between group ${
                    isSelected 
                      ? 'bg-primary/10 border-primary text-primary font-bold'
                      : 'bg-surface-container-low border-outline-variant text-on-surface-variant hover:bg-surface-container-high/60 hover:text-on-surface'
                  }`}
                >
                  <span>{String.fromCharCode(65 + optIdx)}. {opt}</span>
                  <div className={`w-4 h-4 rounded-full border flex items-center justify-center shrink-0 ${
                    isSelected 
                      ? 'border-primary bg-primary text-on-primary' 
                      : 'border-outline-variant group-hover:border-on-surface-variant'
                  }`}>
                    {isSelected && <span className="text-[9px] font-bold">✓</span>}
                  </div>
                </button>
              );
            })}
          </div>

          {/* Navigation Buttons */}
          <div className="flex justify-between items-center pt-4 border-t border-outline-variant">
            <button
              type="button"
              onClick={() => setCurrentQuestionIdx(prev => Math.max(0, prev - 1))}
              disabled={currentQuestionIdx === 0}
              className="px-4 py-2 border border-outline-variant text-on-surface hover:bg-surface-container-high disabled:opacity-30 rounded-lg text-xs font-mono transition-all"
            >
              Previous
            </button>

            {currentQuestionIdx < 9 ? (
              <button
                type="button"
                onClick={() => setCurrentQuestionIdx(prev => Math.min(9, prev + 1))}
                className="px-4 py-2 bg-surface-container-high border border-outline-variant text-on-surface hover:bg-surface-container-highest rounded-lg text-xs font-mono transition-all"
              >
                Next
              </button>
            ) : (
              <button
                type="button"
                onClick={handleSubmitSkillTest}
                disabled={submittingTest || selectedAnswers[9] === undefined}
                className="px-5 py-2.5 bg-primary text-on-primary font-bold hover:brightness-110 active:scale-95 disabled:opacity-50 rounded-lg text-xs font-mono transition-all flex items-center gap-1.5"
              >
                {submittingTest ? (
                  <>
                    <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                    <span>Submitting...</span>
                  </>
                ) : (
                  <>
                    <CheckCircle className="w-3.5 h-3.5" />
                    <span>Submit Test</span>
                  </>
                )}
              </button>
            )}
          </div>
        </div>
      )}

      {/* 3. Test Results Mode */}
      {testResult && (
        <div className="max-w-md mx-auto p-8 bg-surface-container border border-outline-variant rounded-2xl flex flex-col items-center text-center space-y-6 animate-fade-in shadow-2xl">
          <div className={`w-16 h-16 rounded-full flex items-center justify-center ${
            testResult.passed
              ? 'bg-success-container text-on-success-container border border-success/20'
              : 'bg-error-container text-on-error-container border border-error/20'
          }`}>
            <Award className="w-8 h-8" />
          </div>

          <div className="space-y-2">
            <h3 className="text-2xl font-headline font-bold text-on-surface">
              {testResult.passed ? 'Verification Completed!' : 'Not Verified Yet'}
            </h3>
            <p className="text-xs text-on-surface-variant font-mono">
              Tested Skill: {activeTestSkill}
            </p>
          </div>

          <div className="p-4 bg-surface-container-low border border-outline-variant rounded-xl w-full">
            <p className="text-[10px] font-mono text-on-surface-variant uppercase tracking-wider">Your Score</p>
            <p className="text-3xl font-black text-on-surface mt-1">{testResult.percent}%</p>
            <p className="text-[10px] text-secondary font-mono mt-1">
              {testResult.passed ? `Verified Rating Saved: Level ${testResult.rating}/10` : 'Need 70% to verify'}
            </p>
          </div>

          <p className="text-xs text-on-surface-variant leading-relaxed">
            {testResult.passed
              ? `Congratulations! A verified rating of Level ${testResult.rating}/10 has been added to your profile. Recruiters can view this verified rating on your profile.`
              : `You scored ${testResult.percent}%. You need at least 70% to verify this skill — your rating was not changed. You can try the assessment again.`}
          </p>

          <Button
            fullWidth
            onClick={() => {
              setActiveTestSkill(null);
              setTestResult(null);
            }}
          >
            Back to Your Tests
          </Button>
        </div>
      )}

      {/* 4. Skills Dashboard Grid */}
      {!activeTestSkill && !testResult && (
        <div className="space-y-6">
          {/* Filtering Tags */}
          {techSkills.length > 0 && (
            <div className="flex flex-wrap items-center gap-2">
              <button
                type="button"
                onClick={() => setFilter('all')}
                className={`px-3 py-1.5 rounded-full text-xs font-mono transition-all border select-none ${
                  filter === 'all'
                    ? 'bg-primary/10 border-primary text-primary font-bold'
                    : 'bg-surface-container border-outline-variant text-on-surface-variant hover:bg-surface-container-high'
                }`}
              >
                All Skills ({techSkills.length})
              </button>
              <button
                type="button"
                onClick={() => setFilter('verified')}
                className={`px-3 py-1.5 rounded-full text-xs font-mono transition-all border select-none ${
                  filter === 'verified'
                    ? 'bg-success-container border-success/30 text-success font-bold'
                    : 'bg-surface-container border-outline-variant text-on-surface-variant hover:bg-surface-container-high'
                }`}
              >
                Verified ({techSkills.filter(s => s.verifiedRating !== null && s.verifiedRating !== undefined).length})
              </button>
              <button
                type="button"
                onClick={() => setFilter('unverified')}
                className={`px-3 py-1.5 rounded-full text-xs font-mono transition-all border select-none ${
                  filter === 'unverified'
                    ? 'bg-error-container border-error/30 text-error font-bold'
                    : 'bg-surface-container border-outline-variant text-on-surface-variant hover:bg-surface-container-high'
                }`}
              >
                Unverified ({techSkills.filter(s => s.verifiedRating === null || s.verifiedRating === undefined).length})
              </button>
            </div>
          )}

          {loadingTechSkills ? (
            <div className="flex items-center justify-center min-h-[300px]">
              <RefreshCw className="w-8 h-8 animate-spin text-primary" />
            </div>
          ) : techSkills.length > 0 ? (
            (() => {
              const filteredSkills = techSkills.filter(skill => {
                const isVerified = skill.verifiedRating !== null && skill.verifiedRating !== undefined;
                if (filter === 'verified') return isVerified;
                if (filter === 'unverified') return !isVerified;
                return true;
              });

              if (filteredSkills.length === 0) {
                return (
                  <div className="text-center py-16 bg-surface-container border border-outline-variant rounded-2xl">
                    <p className="text-xs text-on-surface-variant italic font-mono">No {filter} skills found.</p>
                  </div>
                );
              }

              return (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {filteredSkills.map((skill, idx) => (
                    <div key={idx} className="p-5 bg-surface-container border border-outline-variant rounded-2xl flex flex-col justify-between h-35 hover:border-primary/20 transition-all">
                      <div className="space-y-2">
                        <div className="flex justify-between items-start">
                          <h4 className="text-base font-bold text-on-surface truncate max-w-[150px] uppercase font-headline">
                            {skill.name}
                          </h4>
                          <span className="px-2 py-0.5 bg-surface-container-high border border-outline-variant rounded text-[9px] font-mono text-on-surface-variant uppercase">
                            Technical
                          </span>
                        </div>
                        
                        <div className="space-y-1 pt-1">
                          <div className="flex justify-between text-[10px] font-mono">
                            <span className="text-on-surface-variant">Verified Rating:</span>
                            {skill.verifiedRating !== null && skill.verifiedRating !== undefined ? (
                              <div className="flex items-center gap-1.5">
                                <span className="text-success font-bold flex items-center gap-0.5">
                                  <ShieldCheck className="w-3.5 h-3.5" /> Lvl {skill.verifiedRating}/10
                                </span>
                              </div>
                            ) : (
                              <span className="text-on-surface-variant italic">Unverified</span>
                            )}
                          </div>
                        </div>
                      </div>

                      <button
                        type="button"
                        onClick={() => handleStartSkillTest(skill.name)}
                        className="w-full py-2 bg-primary/10 border border-primary/20 text-primary font-bold hover:bg-primary text-xs hover:text-on-primary font-mono rounded-lg transition-all"
                      >
                        {skill.verifiedRating !== null && skill.verifiedRating !== undefined ? 'Retake Verification Test' : 'Take Verification Test'}
                      </button>
                    </div>
                  ))}
                </div>
              );
            })()
          ) : (
            <div className="max-w-lg mx-auto">
              <EmptyState
                icon={BookOpen}
                title="No Technical Skills Found"
                description={<>To take a skill verification test, first go to the <strong>Profile & Ratings</strong> section under the Skills tab and self-rate your IT, software, or technical proficiencies.</>}
              />
            </div>
          )}
        </div>
      )}
    </div>
  );
}
