// Domain/field-of-interest options for the student profile searchable dropdown.
// Extracted verbatim from StudentProfile.jsx (static reference data).
export const DOMAIN_OPTIONS = [
  "Software Engineering",
  "Frontend Development",
  "Backend Development",
  "Full Stack Development",
  "Mobile App Development",
  "Game Development",
  "Embedded Systems",
  "IoT Development",
  "Blockchain Development",
  "AR/VR Development",
  "Artificial Intelligence",
  "Machine Learning",
  "Deep Learning",
  "Generative AI",
  "Natural Language Processing",
  "Computer Vision",
  "Data Science",
  "Data Analytics",
  "Business Intelligence",
  "Data Engineering",
  "Cloud Computing",
  "DevOps",
  "Site Reliability Engineering",
  "Cybersecurity",
  "Network Engineering",
  "Database Administration",
  "System Administration",
  "QA Engineering",
  "Automation Testing",
  "Manual Testing",
  "UI Design",
  "UX Design",
  "UI/UX Design",
  "Graphic Design",
  "Motion Graphics",
  "Animation",
  "3D Design",
  "Product Design",
  "Product Management",
  "Project Management",
  "Program Management",
  "Business Analysis",
  "Operations Management",
  "Digital Marketing",
  "Performance Marketing",
  "Content Marketing",
  "SEO",
  "Social Media Marketing",
  "Brand Management",
  "Sales",
  "Business Development",
  "Finance",
  "Accounting",
  "Investment Banking",
  "Human Resources",
  "Recruitment",
  "Customer Success",
  "Customer Support",
  "Consulting",
  "Research",
  "Education",
  "Healthcare",
  "Legal",
  "Supply Chain",
  "Logistics",
  "Manufacturing",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Biomedical Engineering",
  "Aerospace Engineering",
  "Entrepreneurship",
  "Freelancing",
  "Other"
];
