export const INDIAN_STATES = [
  // Famous Districts & Tech Hubs (City, State)
  "Hyderabad, Telangana",
  "Bengaluru, Karnataka",
  "Mumbai, Maharashtra",
  "Pune, Maharashtra",
  "Delhi NCR",
  "Gurugram, Haryana",
  "Noida, Uttar Pradesh",
  "Chennai, Tamil Nadu",
  "Kolkata, West Bengal",
  "Ahmedabad, Gujarat",
  "Jaipur, Rajasthan",
  "Kochi, Kerala",
  "Thiruvananthapuram, Kerala",
  "Indore, Madhya Pradesh",
  "Bhubaneswar, Odisha",
  "Coimbatore, Tamil Nadu",
  "Nagpur, Maharashtra",
  "Visakhapatnam, Andhra Pradesh",
  "Surat, Gujarat",
  "Vadodara, Gujarat",
  "Lucknow, Uttar Pradesh",
  "Kanpur, Uttar Pradesh",
  "Patna, Bihar",
  "Ranchi, Jharkhand",
  "Guwahati, Assam",
  "Dehradun, Uttarakhand",
  "Bhopal, Madhya Pradesh",
  "Mysuru, Karnataka",
  "Mangaluru, Karnataka",
  "Vijayawada, Andhra Pradesh",
  "Warangal, Telangana",
  "Nashik, Maharashtra",
  "Rajkot, Gujarat",
  "Agra, Uttar Pradesh",
  "Varanasi, Uttar Pradesh",
  "Prayagraj, Uttar Pradesh",
  "Amritsar, Punjab",
  "Ludhiana, Punjab",
  "Jodhpur, Rajasthan",
  "Udaipur, Rajasthan",
  "Madurai, Tamil Nadu",
  "Tiruchirappalli, Tamil Nadu",
  "Kozhikode, Kerala",
  "Thrissur, Kerala",

  // Indian States & Union Territories
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal"
];
