export const MAJOR_INDUSTRIES = [
  "Software & Information Technology",
  "Artificial Intelligence & Machine Learning",
  "Financial Services & FinTech",
  "E-Commerce & Retail Tech",
  "Healthcare, BioTech & Pharmaceuticals",
  "EdTech & Educational Services",
  "Cybersecurity & Cloud Infrastructure",
  "Telecommunications & Networking",
  "Media, Entertainment & Gaming",
  "Automotive & Autonomous Mobility",
  "Aerospace & Defense",
  "Renewable Energy & CleanTech",
  "Logistics, Supply Chain & Transportation",
  "Real Estate & PropTech",
  "Manufacturing & Industrial Automation",
  "Agriculture & AgTech",
  "Consulting & Professional Services",
  "Consumer Electronics & Hardware",
  "HRTech & Recruitment Services",
  "Hospitality, Travel & Tourism",
  "Non-Profit & Social Enterprises",
  "Marketing, Advertising & PR",
  "Blockchain, Web3 & Crypto",
  "Semiconductors & Deep Tech",
  "FoodTech & Quick Commerce",
  "Fashion, Apparel & Design",
  "Legal Services & LegalTech",
  "Oil, Gas & Energy Services"
];
