// Master skill reference list (domain data). Each entry tags a skill as
// technical or non-technical. NOTE: keep this in sync with the backend
// TECHNICAL_SKILLS set. Content preserved verbatim (including existing duplicate
// entries) to avoid any behavior change.
export const ALL_SKILLS = [
  { skill: "A2A", type: "technical" },
  { skill: "Accounting", type: "non-technical" },
  { skill: "Agile Methodologies", type: "technical" },
  { skill: "Agile Principles & Scrum", type: "technical" },
  { skill: "Amazon Redshift", type: "technical" },
  { skill: "Analytics", type: "technical" },
  { skill: "AngularJS", type: "technical" },
  { skill: "Ansible", type: "technical" },
  { skill: "Apache Airflow", type: "technical" },
  { skill: "Apache Spark", type: "technical" },
  { skill: "API", type: "technical" },
  { skill: "API testing", type: "technical" },
  { skill: "AWS", type: "technical" },
  { skill: "Azure", type: "technical" },
  { skill: "Bash Scripting", type: "technical" },
  { skill: "BigQuery", type: "technical" },
  { skill: "Bootstrap", type: "technical" },
  { skill: "C", type: "technical" },
  { skill: "C#", type: "technical" },
  { skill: "C++", type: "technical" },
  { skill: "Canva", type: "non-technical" },
  { skill: "Celery", type: "technical" },
  { skill: "Chart.js", type: "technical" },
  { skill: "Claude Code", type: "technical" },
  { skill: "Communication Skills", type: "non-technical" },
  { skill: "Concurrency", type: "technical" },
  { skill: "Creativity", type: "non-technical" },
  { skill: "Crew AI", type: "technical" },
  { skill: "Critical Thinking", type: "non-technical" },
  // { skill: "CSS", type: "technical" },
  { skill: "Cypress", type: "technical" },
  { skill: "Databricks", type: "technical" },
  { skill: "Data Structures & Algorithms", type: "technical" },
  { skill: "Data Warehousing", type: "technical" },
  { skill: "DAX", type: "technical" },
  { skill: "Decision-making", type: "non-technical" },
  { skill: "Deep Learning (DL)", type: "technical" },
  { skill: "Delegating tasks", type: "non-technical" },
  { skill: "Distributed Systems", type: "technical" },
  { skill: "Django", type: "technical" },
  { skill: "Docker", type: "technical" },
  { skill: "Docker Compose", type: "technical" },
  { skill: "Documentation Writing", type: "non-technical" },
  { skill: "Elasticsearch", type: "technical" },
  { skill: "ELK Stack", type: "technical" },
  { skill: "Email Marketing", type: "non-technical" },
  { skill: "Entrepreneurship", type: "non-technical" },
  { skill: "ESLint", type: "technical" },
  { skill: "ETL", type: "technical" },
  { skill: "Event-Driven Architecture", type: "technical" },
  { skill: "Excel", type: "technical" },
  { skill: "Express JS", type: "technical" },
  { skill: "FastAPI", type: "technical" },
  { skill: "Figma", type: "technical" },
  { skill: "Firebase", type: "technical" },
  { skill: "Framer Motion", type: "technical" },
  { skill: "Gemini API", type: "technical" },
  // { skill: "GenAI", type: "technical" },
  { skill: "Generative AI", type: "technical" },
  { skill: "Git and Github", type: "technical" },
  { skill: "GitHub Actions", type: "technical" },
  { skill: "Go", type: "technical" },
  { skill: "Google Analytics", type: "technical" },
  { skill: "Google Cloud Platform", type: "technical" },
  { skill: "Graphic Design", type: "non-technical" },
  { skill: "Hadoop HDFS", type: "technical" },
  { skill: "Haskell", type: "technical" },
  { skill: "Helm", type: "technical" },
  { skill: "HTML", type: "technical" },
  { skill: "Hugging Face", type: "technical" },
  { skill: "Interpersonal communication", type: "non-technical" },
  { skill: "J2EE", type: "technical" },
  { skill: "Jaeger", type: "technical" },
  { skill: "Java", type: "technical" },
  { skill: "JavaScript", type: "technical" },
  { skill: "Jest", type: "technical" },
  { skill: "Jira", type: "technical" },
  { skill: "JQuery", type: "technical" },
  { skill: "Kafka", type: "technical" },
  { skill: "Keras", type: "technical" },
  { skill: "Kubernetes", type: "technical" },
  { skill: "LangChain", type: "technical" },
  { skill: "LangGraph", type: "technical" },
  { skill: "LangSmith", type: "technical" },
  { skill: "Leadership", type: "non-technical" },
  { skill: "LightGBM", type: "technical" },
  { skill: "Linux", type: "technical" },
  { skill: "LLM", type: "technical" },
  { skill: "Machine Learning", type: "technical" },
  { skill: "Makefiles", type: "technical" },
  { skill: "Seaborn", type: "technical" },
  { skill: "Matplotlib", type: "technical" },
  { skill: "MCP", type: "technical" },
  { skill: "Microsoft Office", type: "non-technical" },
  { skill: "MLflow", type: "technical" },
  { skill: "MongoDB", type: "technical" },
  { skill: "MySQL", type: "technical" },
  { skill: "n8n", type: "technical" },
  { skill: "Natural Language Processing", type: "technical" },
  { skill: "Natural Language Toolkit (NLTK)", type: "technical" },
  { skill: ".Net", type: "technical" },
  { skill: "Next.js", type: "technical" },
  // { skill: "Next JS", type: "technical" },
  { skill: "Nginx", type: "technical" },
  { skill: "Node.js", type: "technical" },
  { skill: "NoSQL", type: "technical" },
  { skill: "NumPy", type: "technical" },
  { skill: "OAuth 2.0", type: "technical" },
  { skill: "OpenAI API", type: "technical" },
  { skill: "OpenCV", type: "technical" },
  { skill: "Openness", type: "non-technical" },
  { skill: "Pandas", type: "technical" },
  { skill: "People skills", type: "non-technical" },
  { skill: "Perl", type: "technical" },
  { skill: "Photoshop", type: "non-technical" },
  { skill: "PHP", type: "technical" },
  { skill: "Pinecone", type: "technical" },
  { skill: "Playwright", type: "technical" },
  { skill: "PostgreSQL", type: "technical" },
  { skill: "Postman", type: "technical" },
  { skill: "Power BI", type: "technical" },
  { skill: "Presentation Skills", type: "non-technical" },
  { skill: "Prisma ORM", type: "technical" },
  { skill: "Problem-Solving", type: "non-technical" },
  { skill: "Product Management", type: "non-technical" },
  { skill: "Prometheus", type: "technical" },
  { skill: "Public speaking", type: "non-technical" },
  { skill: "Pyspark", type: "technical" },
  { skill: "Python", type: "technical" },
  { skill: "PyTorch", type: "technical" },
  { skill: "RabbitMQ", type: "technical" },
  { skill: "RAG", type: "technical" },
  // { skill: "React", type: "technical" },
  { skill: "React Native", type: "technical" },
  { skill: "React Testing Library", type: "technical" },
  { skill: "RedHat Linux 7.5", type: "technical" },
  { skill: "Redux", type: "technical" },
  { skill: "Research", type: "non-technical" },
  { skill: "Responsibility", type: "non-technical" },
  { skill: "Ruby", type: "technical" },
  { skill: "Rust", type: "technical" },
  { skill: "Scikit-learn", type: "technical" },
  { skill: "SciPy", type: "technical" },
  { skill: "Sentry", type: "technical" },
  { skill: "SEO/SEM marketing", type: "non-technical" },
  { skill: "ServiceNow", type: "technical" },
  { skill: "Snowflake", type: "technical" },
  { skill: "Social Media", type: "non-technical" },
  { skill: "Spreadsheet", type: "technical" },
  { skill: "SQL", type: "technical" },
  { skill: "Storybook", type: "technical" },
  { skill: "Supabase", type: "technical" },
  { skill: "Swagger", type: "technical" },
  { skill: "Swift", type: "technical" },
  { skill: "CSS", type: "technical" },
  { skill: "Tailwind", type: "technical" },
  { skill: "Tailwind", type: "technical" },
  { skill: "Team Building", type: "non-technical" },
  { skill: "Teamwork", type: "non-technical" },
  { skill: "TensorFlow", type: "technical" },
  { skill: "Terraform", type: "technical" },
  { skill: "Three.js", type: "technical" },
  { skill: "Time management", type: "non-technical" },
  { skill: "Transformers", type: "technical" },
  { skill: "Turborepo", type: "technical" },
  { skill: "TypeScript", type: "technical" },
  { skill: "UI/UX", type: "technical" },
  { skill: "Unit Testing", type: "technical" },
  { skill: "UNIX", type: "technical" },
  { skill: "Vector Embeddings", type: "technical" },
  { skill: "Verbal/nonverbal communication", type: "non-technical" },
  { skill: "Virtualization", type: "technical" },
  { skill: "Vue.js", type: "technical" },
  { skill: "Windows", type: "technical" },
  { skill: "Written communication", type: "non-technical" },
  { skill: "YUM", type: "technical" },
  { skill: "Zustand", type: "technical" }
];
